# -*- coding: utf-8 -*-
"""assignment4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1minMMCLaj-2ssYV1FSZiqvcM6k-FZCyg
"""

import pandas as pd
import numpy as np
from scipy.stats import beta
import matplotlib.pyplot as plt

data = pd.read_csv("https://raw.githubusercontent.com/dustywhite7/Econ8310/master/AssignmentData/cookie_cats.csv")

data["retention_1"] = data["retention_1"].astype(int)
data["retention_7"] = data["retention_7"].astype(int)

print(data.head())

control = data[data["version"] == "gate_30"]
treatment = data[data["version"] == "gate_40"]

cRetention_1 = control["retention_1"].mean()
tRetention_1 = treatment["retention_1"].mean()

cRetention_7 = control["retention_7"].mean()
tRetention_7 = treatment["retention_7"].mean()

print(f"Gate 30 1-day Retention: {cRetention_1:.2f}")
print(f"Gate 40 1-day Retention: {tRetention_1:.2f}")
print(f"Gate 30 7-day Retention: {cRetention_7:.2f}")
print(f"Gate 40 7-day Retention: {tRetention_7:.2f}")